name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: AWS Config
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache-backend
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - name: Build Lambda
        run: |
          cd ./server/app
          bun install
          bun run build
          cd dist
          zip -j ../lambda.zip index.js

      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION_NAME }} \
            --zip-file fileb://./server/app/lambda.zip
      - uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache-frontend
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
      - run: |
          cd ./client
          bun install
          VITE_API_URL=${{ secrets.API_URL }}
          bun run build
          cp -r public/* dist/

      - name: Push to S3
        run: |
          aws s3 sync ./client/dist s3://${{ secrets.S3_BUCKET_NAME }} --delete

      - name: Register blog posts
        run: |
          echo ${{ secrets.API_URL}}
          for file in blogs/*.md; do
            slug=$(basename "$file" .md)
            title=$(grep '^title:' "$file" | sed 's/^title: *"//;s/"$//')
            curl -s -o /dev/null -w "%{http_code}" \
              -X POST "${{ secrets.API_URL }}/blog/" \
              -H "Content-Type: application/json" \
              -d "{\"title\": \"$title\", \"slug\": \"$slug\"}" || true
          done

      - name: Purge Cache
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_ID }} --paths "/*"
